export enum CoinKey {
	ETH = 'ETH',
	MATIC = 'MATIC',
	BNB = 'BNB',
	DAI = 'DAI',
	FTM = 'FTM',
	OKT = 'OKT',
	AVAX = 'AVAX',
	HT = 'HT',
	ONE = 'ONE',
	FSN = 'FSN',
	MOVR = 'MOVR',
	EXP = 'EXP',
	TCH = 'TCH',
	UBQ = 'UBQ',
	META = 'META',
	DIODE = 'DIODE',
	CELO = 'CELO',
	FUSE = 'FUSE',
	TLOS = 'TLOS',
	CRO = 'CRO',
	SHIB = 'SHIB',
	L1 = 'L1',
	RBTC = 'RBTC',
	TBG = 'TBG',
	VLX = 'VLX',
	GLMR = 'GLMR',
	METIS = 'METIS',
	SOL = 'SOL',
  
	// Stable coins
	USDT = 'USDT',
	USDC = 'USDC',
  
	// Testnet
	TEST = 'TEST',
	KAL = 'KAL',
	SDIODE = 'SDIODE',
	SPARK = 'SPARK',
	TRBTC = 'TRBTC',
  
	// Other tokens
	WBTC = 'WBTC',
	WETH = 'WETH',
	SUSHI = 'SUSHI',
	DODO = 'DODO',
	MCB = 'MCB',
	CELR = 'CELR',
	IF = 'IF',
  }